--liquibase formatted sql

--changeset gdamiens:drop-legacy-referential
--comment: Lines and stops now come from the gtfs schema; test was a PostGIS sandbox
DROP TABLE IF EXISTS public.idfm_stop_in_line;
DROP TABLE IF EXISTS public.idfm_line;
DROP TABLE IF EXISTS public.idfm_operator;
DROP TABLE IF EXISTS public.idfm_stop;
DROP TABLE IF EXISTS public.test;

--changeset gdamiens:user-id-identity
--comment: Replace the Hibernate user_seq sequence by an identity column
ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public."user"', 'id'), COALESCE(max(id), 0) + 1, false) FROM public."user";
DROP SEQUENCE IF EXISTS public.user_seq;
