--liquibase formatted sql

--changeset gdamiens:user-role-email
--comment: Public sign-up: users get a role (existing accounts stay admin), an optional unique email and a creation date
ALTER TABLE public."user" ADD COLUMN role varchar(32);
UPDATE public."user" SET role = 'ROLE_ADMIN';
ALTER TABLE public."user" ALTER COLUMN role SET NOT NULL;
ALTER TABLE public."user" ALTER COLUMN role SET DEFAULT 'ROLE_USER';
ALTER TABLE public."user" ADD COLUMN email varchar(255);
ALTER TABLE public."user" ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX user_login_key ON public."user" (lower(login));
CREATE UNIQUE INDEX user_email_key ON public."user" (lower(email));

--changeset gdamiens:refresh-token
--comment: Long-lived refresh tokens (only their SHA-256 hash is stored), rotated on each use
CREATE TABLE public.refresh_token (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer      NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    token_hash  varchar(64)  NOT NULL UNIQUE,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    expires_at  timestamptz  NOT NULL,
    revoked_at  timestamptz
);
CREATE INDEX refresh_token_user_id_idx ON public.refresh_token (user_id);
