/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import io.swagger.client.model.EquipmentReports;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EquipmentReportsApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public EquipmentReportsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EquipmentReportsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for getCoordLonLatEquipmentReports
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoordLonLatEquipmentReportsCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coord/{lon};{lat}/equipment_reports"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoordLonLatEquipmentReportsValidateBeforeCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoordLonLatEquipmentReports(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoordLonLatEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoordLonLatEquipmentReportsCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoordLonLatEquipmentReports(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoordLonLatEquipmentReportsWithHttpInfo(lon, lat, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoordLonLatEquipmentReportsWithHttpInfo(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoordLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoordLonLatEquipmentReportsAsync(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoordLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoordsLonLatEquipmentReports
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoordsLonLatEquipmentReportsCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coords/{lon};{lat}/equipment_reports"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoordsLonLatEquipmentReportsValidateBeforeCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoordsLonLatEquipmentReports(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoordsLonLatEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoordsLonLatEquipmentReportsCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoordsLonLatEquipmentReports(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoordsLonLatEquipmentReportsWithHttpInfo(lon, lat, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoordsLonLatEquipmentReportsWithHttpInfo(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoordsLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoordsLonLatEquipmentReportsAsync(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoordsLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageLonLatEquipmentReports
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatEquipmentReportsCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{lon};{lat}/equipment_reports"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageLonLatEquipmentReportsValidateBeforeCall(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoverageLonLatEquipmentReports(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoverageLonLatEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageLonLatEquipmentReportsCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoverageLonLatEquipmentReports(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoverageLonLatEquipmentReportsWithHttpInfo(lon, lat, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoverageLonLatEquipmentReportsWithHttpInfo(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatEquipmentReportsAsync(BigDecimal lon, BigDecimal lat, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageLonLatEquipmentReportsValidateBeforeCall(lon, lat, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageLonLatUriEquipmentReports
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatUriEquipmentReportsCall(BigDecimal lon, BigDecimal lat, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{lon};{lat}/{uri}/equipment_reports"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()))
            .replaceAll("\\{" + "uri" + "\\}", apiClient.escapeString(uri.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageLonLatUriEquipmentReportsValidateBeforeCall(BigDecimal lon, BigDecimal lat, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoverageLonLatUriEquipmentReports(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoverageLonLatUriEquipmentReports(Async)");
        }

        // verify the required parameter 'uri' is set
        if (uri == null) {
            throw new ApiException("Missing the required parameter 'uri' when calling getCoverageLonLatUriEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageLonLatUriEquipmentReportsCall(lon, lat, uri, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoverageLonLatUriEquipmentReports(BigDecimal lon, BigDecimal lat, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoverageLonLatUriEquipmentReportsWithHttpInfo(lon, lat, uri, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoverageLonLatUriEquipmentReportsWithHttpInfo(BigDecimal lon, BigDecimal lat, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageLonLatUriEquipmentReportsValidateBeforeCall(lon, lat, uri, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatUriEquipmentReportsAsync(BigDecimal lon, BigDecimal lat, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageLonLatUriEquipmentReportsValidateBeforeCall(lon, lat, uri, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageRegionEquipmentReports
     * @param region The region you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionEquipmentReportsCall(String region, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{region}/equipment_reports"
            .replaceAll("\\{" + "region" + "\\}", apiClient.escapeString(region.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageRegionEquipmentReportsValidateBeforeCall(String region, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'region' is set
        if (region == null) {
            throw new ApiException("Missing the required parameter 'region' when calling getCoverageRegionEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageRegionEquipmentReportsCall(region, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoverageRegionEquipmentReports(String region, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoverageRegionEquipmentReportsWithHttpInfo(region, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoverageRegionEquipmentReportsWithHttpInfo(String region, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageRegionEquipmentReportsValidateBeforeCall(region, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param region The region you want to query (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionEquipmentReportsAsync(String region, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageRegionEquipmentReportsValidateBeforeCall(region, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageRegionUriEquipmentReports
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionUriEquipmentReportsCall(String region, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{region}/{uri}/equipment_reports"
            .replaceAll("\\{" + "region" + "\\}", apiClient.escapeString(region.toString()))
            .replaceAll("\\{" + "uri" + "\\}", apiClient.escapeString(uri.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (depth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("depth", depth));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("filter", filter));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));
        if (forbiddenUris != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "forbidden_uris[]", forbiddenUris));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageRegionUriEquipmentReportsValidateBeforeCall(String region, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'region' is set
        if (region == null) {
            throw new ApiException("Missing the required parameter 'region' when calling getCoverageRegionUriEquipmentReports(Async)");
        }

        // verify the required parameter 'uri' is set
        if (uri == null) {
            throw new ApiException("Missing the required parameter 'uri' when calling getCoverageRegionUriEquipmentReports(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageRegionUriEquipmentReportsCall(region, uri, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return EquipmentReports
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EquipmentReports getCoverageRegionUriEquipmentReports(String region, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        ApiResponse<EquipmentReports> resp = getCoverageRegionUriEquipmentReportsWithHttpInfo(region, uri, depth, count, filter, startPage, forbiddenUris);
        return resp.getData();
    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @return ApiResponse&lt;EquipmentReports&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EquipmentReports> getCoverageRegionUriEquipmentReportsWithHttpInfo(String region, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageRegionUriEquipmentReportsValidateBeforeCall(region, uri, depth, count, filter, startPage, forbiddenUris, null, null);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param depth The depth of your object (optional, default to 1)
     * @param count Number of objects per page (optional, default to 25)
     * @param filter Filter your objects (optional)
     * @param startPage The current page (optional)
     * @param forbiddenUris forbidden uris (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionUriEquipmentReportsAsync(String region, String uri, Integer depth, Integer count, String filter, Integer startPage, List<String> forbiddenUris, final ApiCallback<EquipmentReports> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageRegionUriEquipmentReportsValidateBeforeCall(region, uri, depth, count, filter, startPage, forbiddenUris, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EquipmentReports>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
