/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import io.swagger.client.model.Obstacles;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ObstaclesNearbyApi {
    private ApiClient apiClient;
    private Map<String, String> headers;

    public ObstaclesNearbyApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ObstaclesNearbyApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public void setHeadersOverrides(Map<String, String> headers) {
        this.headers = headers;
    }

    /**
     * Build call for getCoordLonLatObstaclesNearby
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoordLonLatObstaclesNearbyCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coord/{lon};{lat}/obstacles_nearby"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoordLonLatObstaclesNearbyValidateBeforeCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoordLonLatObstaclesNearby(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoordLonLatObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoordLonLatObstaclesNearbyCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoordLonLatObstaclesNearby(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoordLonLatObstaclesNearbyWithHttpInfo(lon, lat, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoordLonLatObstaclesNearbyWithHttpInfo(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoordLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoordLonLatObstaclesNearbyAsync(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoordLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoordsLonLatObstaclesNearby
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoordsLonLatObstaclesNearbyCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coords/{lon};{lat}/obstacles_nearby"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoordsLonLatObstaclesNearbyValidateBeforeCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoordsLonLatObstaclesNearby(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoordsLonLatObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoordsLonLatObstaclesNearbyCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoordsLonLatObstaclesNearby(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoordsLonLatObstaclesNearbyWithHttpInfo(lon, lat, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoordsLonLatObstaclesNearbyWithHttpInfo(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoordsLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoordsLonLatObstaclesNearbyAsync(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoordsLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageLonLatObstaclesNearby
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatObstaclesNearbyCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{lon};{lat}/obstacles_nearby"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageLonLatObstaclesNearbyValidateBeforeCall(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoverageLonLatObstaclesNearby(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoverageLonLatObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageLonLatObstaclesNearbyCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoverageLonLatObstaclesNearby(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoverageLonLatObstaclesNearbyWithHttpInfo(lon, lat, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoverageLonLatObstaclesNearbyWithHttpInfo(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatObstaclesNearbyAsync(BigDecimal lon, BigDecimal lat, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageLonLatObstaclesNearbyValidateBeforeCall(lon, lat, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageLonLatUriObstaclesNearby
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatUriObstaclesNearbyCall(BigDecimal lon, BigDecimal lat, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{lon};{lat}/{uri}/obstacles_nearby"
            .replaceAll("\\{" + "lon" + "\\}", apiClient.escapeString(lon.toString()))
            .replaceAll("\\{" + "lat" + "\\}", apiClient.escapeString(lat.toString()))
            .replaceAll("\\{" + "uri" + "\\}", apiClient.escapeString(uri.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageLonLatUriObstaclesNearbyValidateBeforeCall(BigDecimal lon, BigDecimal lat, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getCoverageLonLatUriObstaclesNearby(Async)");
        }

        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getCoverageLonLatUriObstaclesNearby(Async)");
        }

        // verify the required parameter 'uri' is set
        if (uri == null) {
            throw new ApiException("Missing the required parameter 'uri' when calling getCoverageLonLatUriObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageLonLatUriObstaclesNearbyCall(lon, lat, uri, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoverageLonLatUriObstaclesNearby(BigDecimal lon, BigDecimal lat, String uri, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoverageLonLatUriObstaclesNearbyWithHttpInfo(lon, lat, uri, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoverageLonLatUriObstaclesNearbyWithHttpInfo(BigDecimal lon, BigDecimal lat, String uri, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageLonLatUriObstaclesNearbyValidateBeforeCall(lon, lat, uri, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param lon The longitude of where the coord you want to query (required)
     * @param lat The latitude of where the coord you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageLonLatUriObstaclesNearbyAsync(BigDecimal lon, BigDecimal lat, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageLonLatUriObstaclesNearbyValidateBeforeCall(lon, lat, uri, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageRegionObstaclesNearby
     * @param region The region you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionObstaclesNearbyCall(String region, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{region}/obstacles_nearby"
            .replaceAll("\\{" + "region" + "\\}", apiClient.escapeString(region.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageRegionObstaclesNearbyValidateBeforeCall(String region, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'region' is set
        if (region == null) {
            throw new ApiException("Missing the required parameter 'region' when calling getCoverageRegionObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageRegionObstaclesNearbyCall(region, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoverageRegionObstaclesNearby(String region, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoverageRegionObstaclesNearbyWithHttpInfo(region, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoverageRegionObstaclesNearbyWithHttpInfo(String region, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageRegionObstaclesNearbyValidateBeforeCall(region, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param region The region you want to query (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionObstaclesNearbyAsync(String region, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageRegionObstaclesNearbyValidateBeforeCall(region, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getCoverageRegionUriObstaclesNearby
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionUriObstaclesNearbyCall(String region, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/coverage/{region}/{uri}/obstacles_nearby"
            .replaceAll("\\{" + "region" + "\\}", apiClient.escapeString(region.toString()))
            .replaceAll("\\{" + "uri" + "\\}", apiClient.escapeString(uri.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (path != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("path", path));
        if (distance != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("distance", distance));
        if (count != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("count", count));
        if (coord != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("coord", coord));
        if (startPage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("start_page", startPage));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        if (headers != null) {
            localVarHeaderParams.putAll(headers);
        }
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getCoverageRegionUriObstaclesNearbyValidateBeforeCall(String region, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        // verify the required parameter 'region' is set
        if (region == null) {
            throw new ApiException("Missing the required parameter 'region' when calling getCoverageRegionUriObstaclesNearby(Async)");
        }

        // verify the required parameter 'uri' is set
        if (uri == null) {
            throw new ApiException("Missing the required parameter 'uri' when calling getCoverageRegionUriObstaclesNearby(Async)");
        }


        com.squareup.okhttp.Call call = getCoverageRegionUriObstaclesNearbyCall(region, uri, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        return call;

    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return Obstacles
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Obstacles getCoverageRegionUriObstaclesNearby(String region, String uri, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        ApiResponse<Obstacles> resp = getCoverageRegionUriObstaclesNearbyWithHttpInfo(region, uri, path, distance, count, coord, startPage);
        return resp.getData();
    }

    /**
     *
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @return ApiResponse&lt;Obstacles&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Obstacles> getCoverageRegionUriObstaclesNearbyWithHttpInfo(String region, String uri, String path, Integer distance, Integer count, String coord, Integer startPage) throws ApiException {
        com.squareup.okhttp.Call call = getCoverageRegionUriObstaclesNearbyValidateBeforeCall(region, uri, path, distance, count, coord, startPage, null, null);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     *
     * @param region The region you want to query (required)
     * @param uri First part of the uri (required)
     * @param path A geojson in polyline path as base64 (optional)
     * @param distance Distance range of the query in meters (optional, default to 500)
     * @param count Elements per page (optional, default to 10)
     * @param coord Coordinates longitude;latitude used to search the objects around this coordinate (optional)
     * @param startPage The current page (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getCoverageRegionUriObstaclesNearbyAsync(String region, String uri, String path, Integer distance, Integer count, String coord, Integer startPage, final ApiCallback<Obstacles> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getCoverageRegionUriObstaclesNearbyValidateBeforeCall(region, uri, path, distance, count, coord, startPage, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Obstacles>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
