/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CellLonSchema
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class CellLonSchema {
  @SerializedName("center_lon")
  private Float centerLon = null;

  @SerializedName("max_lon")
  private Float maxLon = null;

  @SerializedName("min_lon")
  private Float minLon = null;

  public CellLonSchema centerLon(Float centerLon) {
    this.centerLon = centerLon;
    return this;
  }

   /**
   * Get centerLon
   * @return centerLon
  **/
  @ApiModelProperty(value = "")
  public Float getCenterLon() {
    return centerLon;
  }

  public void setCenterLon(Float centerLon) {
    this.centerLon = centerLon;
  }

  public CellLonSchema maxLon(Float maxLon) {
    this.maxLon = maxLon;
    return this;
  }

   /**
   * Get maxLon
   * @return maxLon
  **/
  @ApiModelProperty(value = "")
  public Float getMaxLon() {
    return maxLon;
  }

  public void setMaxLon(Float maxLon) {
    this.maxLon = maxLon;
  }

  public CellLonSchema minLon(Float minLon) {
    this.minLon = minLon;
    return this;
  }

   /**
   * Get minLon
   * @return minLon
  **/
  @ApiModelProperty(value = "")
  public Float getMinLon() {
    return minLon;
  }

  public void setMinLon(Float minLon) {
    this.minLon = minLon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellLonSchema cellLonSchema = (CellLonSchema) o;
    return Objects.equals(this.centerLon, cellLonSchema.centerLon) &&
        Objects.equals(this.maxLon, cellLonSchema.maxLon) &&
        Objects.equals(this.minLon, cellLonSchema.minLon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(centerLon, maxLon, minLon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellLonSchema {\n");

    sb.append("    centerLon: ").append(toIndentedString(centerLon)).append("\n");
    sb.append("    maxLon: ").append(toIndentedString(maxLon)).append("\n");
    sb.append("    minLon: ").append(toIndentedString(minLon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

