/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Context;
import io.swagger.client.model.GeoStatus;
import java.io.IOException;

/**
 * GeoStatus1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class GeoStatus1 {
  @SerializedName("geo_status")
  private GeoStatus geoStatus = null;

  @SerializedName("context")
  private Context context = null;

  public GeoStatus1 geoStatus(GeoStatus geoStatus) {
    this.geoStatus = geoStatus;
    return this;
  }

   /**
   * Get geoStatus
   * @return geoStatus
  **/
  @ApiModelProperty(required = true, value = "")
  public GeoStatus getGeoStatus() {
    return geoStatus;
  }

  public void setGeoStatus(GeoStatus geoStatus) {
    this.geoStatus = geoStatus;
  }

  public GeoStatus1 context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoStatus1 geoStatus1 = (GeoStatus1) o;
    return Objects.equals(this.geoStatus, geoStatus1.geoStatus) &&
        Objects.equals(this.context, geoStatus1.context);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geoStatus, context);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoStatus1 {\n");

    sb.append("    geoStatus: ").append(toIndentedString(geoStatus)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

