/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Context;
import io.swagger.client.model.Disruption;
import io.swagger.client.model.Error;
import io.swagger.client.model.Exception;
import io.swagger.client.model.FeedPublisher;
import io.swagger.client.model.Journey;
import io.swagger.client.model.LinkSchema;
import io.swagger.client.model.Note;
import io.swagger.client.model.StopArea;
import io.swagger.client.model.Ticket;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Journeys
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class Journeys {
  @SerializedName("error")
  private Error error = null;

  @SerializedName("feed_publishers")
  private List<FeedPublisher> feedPublishers = new ArrayList<FeedPublisher>();

  @SerializedName("links")
  private List<LinkSchema> links = new ArrayList<LinkSchema>();

  @SerializedName("journeys")
  private List<Journey> journeys = null;

  @SerializedName("tickets")
  private List<Ticket> tickets = new ArrayList<Ticket>();

  @SerializedName("disruptions")
  private List<Disruption> disruptions = new ArrayList<Disruption>();

  @SerializedName("terminus")
  private List<StopArea> terminus = new ArrayList<StopArea>();

  @SerializedName("context")
  private Context context = null;

  @SerializedName("notes")
  private List<Note> notes = null;

  @SerializedName("exceptions")
  private List<Exception> exceptions = null;

  public Journeys error(Error error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }

  public Journeys feedPublishers(List<FeedPublisher> feedPublishers) {
    this.feedPublishers = feedPublishers;
    return this;
  }

  public Journeys addFeedPublishersItem(FeedPublisher feedPublishersItem) {
    this.feedPublishers.add(feedPublishersItem);
    return this;
  }

   /**
   * Get feedPublishers
   * @return feedPublishers
  **/
  @ApiModelProperty(required = true, value = "")
  public List<FeedPublisher> getFeedPublishers() {
    return feedPublishers;
  }

  public void setFeedPublishers(List<FeedPublisher> feedPublishers) {
    this.feedPublishers = feedPublishers;
  }

  public Journeys links(List<LinkSchema> links) {
    this.links = links;
    return this;
  }

  public Journeys addLinksItem(LinkSchema linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "")
  public List<LinkSchema> getLinks() {
    return links;
  }

  public void setLinks(List<LinkSchema> links) {
    this.links = links;
  }

  public Journeys journeys(List<Journey> journeys) {
    this.journeys = journeys;
    return this;
  }

  public Journeys addJourneysItem(Journey journeysItem) {
    if (this.journeys == null) {
      this.journeys = new ArrayList<Journey>();
    }
    this.journeys.add(journeysItem);
    return this;
  }

   /**
   * Get journeys
   * @return journeys
  **/
  @ApiModelProperty(value = "")
  public List<Journey> getJourneys() {
    return journeys;
  }

  public void setJourneys(List<Journey> journeys) {
    this.journeys = journeys;
  }

  public Journeys tickets(List<Ticket> tickets) {
    this.tickets = tickets;
    return this;
  }

  public Journeys addTicketsItem(Ticket ticketsItem) {
    this.tickets.add(ticketsItem);
    return this;
  }

   /**
   * Get tickets
   * @return tickets
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Ticket> getTickets() {
    return tickets;
  }

  public void setTickets(List<Ticket> tickets) {
    this.tickets = tickets;
  }

  public Journeys disruptions(List<Disruption> disruptions) {
    this.disruptions = disruptions;
    return this;
  }

  public Journeys addDisruptionsItem(Disruption disruptionsItem) {
    this.disruptions.add(disruptionsItem);
    return this;
  }

   /**
   * Get disruptions
   * @return disruptions
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Disruption> getDisruptions() {
    return disruptions;
  }

  public void setDisruptions(List<Disruption> disruptions) {
    this.disruptions = disruptions;
  }

  public Journeys terminus(List<StopArea> terminus) {
    this.terminus = terminus;
    return this;
  }

  public Journeys addTerminusItem(StopArea terminusItem) {
    this.terminus.add(terminusItem);
    return this;
  }

   /**
   * Get terminus
   * @return terminus
  **/
  @ApiModelProperty(required = true, value = "")
  public List<StopArea> getTerminus() {
    return terminus;
  }

  public void setTerminus(List<StopArea> terminus) {
    this.terminus = terminus;
  }

  public Journeys context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }

  public Journeys notes(List<Note> notes) {
    this.notes = notes;
    return this;
  }

  public Journeys addNotesItem(Note notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<Note>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public List<Note> getNotes() {
    return notes;
  }

  public void setNotes(List<Note> notes) {
    this.notes = notes;
  }

  public Journeys exceptions(List<Exception> exceptions) {
    this.exceptions = exceptions;
    return this;
  }

  public Journeys addExceptionsItem(Exception exceptionsItem) {
    if (this.exceptions == null) {
      this.exceptions = new ArrayList<Exception>();
    }
    this.exceptions.add(exceptionsItem);
    return this;
  }

   /**
   * Get exceptions
   * @return exceptions
  **/
  @ApiModelProperty(value = "")
  public List<Exception> getExceptions() {
    return exceptions;
  }

  public void setExceptions(List<Exception> exceptions) {
    this.exceptions = exceptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Journeys journeys = (Journeys) o;
    return Objects.equals(this.error, journeys.error) &&
        Objects.equals(this.feedPublishers, journeys.feedPublishers) &&
        Objects.equals(this.links, journeys.links) &&
        Objects.equals(this.journeys, journeys.journeys) &&
        Objects.equals(this.tickets, journeys.tickets) &&
        Objects.equals(this.disruptions, journeys.disruptions) &&
        Objects.equals(this.terminus, journeys.terminus) &&
        Objects.equals(this.context, journeys.context) &&
        Objects.equals(this.notes, journeys.notes) &&
        Objects.equals(this.exceptions, journeys.exceptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, feedPublishers, links, journeys, tickets, disruptions, terminus, context, notes, exceptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Journeys {\n");

    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    feedPublishers: ").append(toIndentedString(feedPublishers)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    journeys: ").append(toIndentedString(journeys)).append("\n");
    sb.append("    tickets: ").append(toIndentedString(tickets)).append("\n");
    sb.append("    disruptions: ").append(toIndentedString(disruptions)).append("\n");
    sb.append("    terminus: ").append(toIndentedString(terminus)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    exceptions: ").append(toIndentedString(exceptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

