/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AirPollutants;
import io.swagger.client.model.Amount;
import io.swagger.client.model.Calendar;
import io.swagger.client.model.Distances;
import io.swagger.client.model.Durations;
import io.swagger.client.model.Fare;
import io.swagger.client.model.JourneyDebug;
import io.swagger.client.model.LinkSchema;
import io.swagger.client.model.LowEmissionZone;
import io.swagger.client.model.Place;
import io.swagger.client.model.Section;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Journey
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class Journey {
  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("nb_transfers")
  private Integer nbTransfers = null;

  @SerializedName("departure_date_time")
  private String departureDateTime = null;

  @SerializedName("arrival_date_time")
  private String arrivalDateTime = null;

  @SerializedName("requested_date_time")
  private String requestedDateTime = null;

  @SerializedName("to")
  private Place to = null;

  @SerializedName("from")
  private Place from = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("co2_emission")
  private Amount co2Emission = null;

  @SerializedName("air_pollutants")
  private AirPollutants airPollutants = null;

  @SerializedName("low_emission_zone")
  private LowEmissionZone lowEmissionZone = null;

  @SerializedName("durations")
  private Durations durations = null;

  @SerializedName("distances")
  private Distances distances = null;

  @SerializedName("fare")
  private Fare fare = null;

  @SerializedName("calendars")
  private List<Calendar> calendars = null;

  @SerializedName("sections")
  private List<Section> sections = null;

  @SerializedName("debug")
  private JourneyDebug debug = null;

  @SerializedName("links")
  private List<LinkSchema> links = null;

  public Journey duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of the journey (seconds)
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "Duration of the journey (seconds)")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public Journey nbTransfers(Integer nbTransfers) {
    this.nbTransfers = nbTransfers;
    return this;
  }

   /**
   * Number of transfers along the journey
   * @return nbTransfers
  **/
  @ApiModelProperty(required = true, value = "Number of transfers along the journey")
  public Integer getNbTransfers() {
    return nbTransfers;
  }

  public void setNbTransfers(Integer nbTransfers) {
    this.nbTransfers = nbTransfers;
  }

  public Journey departureDateTime(String departureDateTime) {
    this.departureDateTime = departureDateTime;
    return this;
  }

   /**
   * Departure date and time of the journey
   * @return departureDateTime
  **/
  @ApiModelProperty(value = "Departure date and time of the journey")
  public String getDepartureDateTime() {
    return departureDateTime;
  }

  public void setDepartureDateTime(String departureDateTime) {
    this.departureDateTime = departureDateTime;
  }

  public Journey arrivalDateTime(String arrivalDateTime) {
    this.arrivalDateTime = arrivalDateTime;
    return this;
  }

   /**
   * Arrival date and time of the journey
   * @return arrivalDateTime
  **/
  @ApiModelProperty(value = "Arrival date and time of the journey")
  public String getArrivalDateTime() {
    return arrivalDateTime;
  }

  public void setArrivalDateTime(String arrivalDateTime) {
    this.arrivalDateTime = arrivalDateTime;
  }

  public Journey requestedDateTime(String requestedDateTime) {
    this.requestedDateTime = requestedDateTime;
    return this;
  }

   /**
   * Get requestedDateTime
   * @return requestedDateTime
  **/
  @ApiModelProperty(value = "")
  public String getRequestedDateTime() {
    return requestedDateTime;
  }

  public void setRequestedDateTime(String requestedDateTime) {
    this.requestedDateTime = requestedDateTime;
  }

  public Journey to(Place to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public Place getTo() {
    return to;
  }

  public void setTo(Place to) {
    this.to = to;
  }

  public Journey from(Place from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(value = "")
  public Place getFrom() {
    return from;
  }

  public void setFrom(Place from) {
    this.from = from;
  }

  public Journey type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Used to qualify the journey (can be \&quot;best\&quot;, \&quot;comfort\&quot;, \&quot;non_pt_walk\&quot;, ...
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Used to qualify the journey (can be \"best\", \"comfort\", \"non_pt_walk\", ...")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Journey status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status from the whole journey taking into account the most disturbing information retrieved on PT object used (can be \&quot;NO_SERVICE\&quot;, \&quot;SIGNIFICANT_DELAYS\&quot;, ...). A base-schedule journey using a stop-time that is deleted in realtime will have a NO_SERVICE status (no matter the effect of the disruption causing it).
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status from the whole journey taking into account the most disturbing information retrieved on PT object used (can be \"NO_SERVICE\", \"SIGNIFICANT_DELAYS\", ...). A base-schedule journey using a stop-time that is deleted in realtime will have a NO_SERVICE status (no matter the effect of the disruption causing it).")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Journey tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Journey addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public Journey co2Emission(Amount co2Emission) {
    this.co2Emission = co2Emission;
    return this;
  }

   /**
   * Get co2Emission
   * @return co2Emission
  **/
  @ApiModelProperty(required = true, value = "")
  public Amount getCo2Emission() {
    return co2Emission;
  }

  public void setCo2Emission(Amount co2Emission) {
    this.co2Emission = co2Emission;
  }

  public Journey airPollutants(AirPollutants airPollutants) {
    this.airPollutants = airPollutants;
    return this;
  }

   /**
   * Get airPollutants
   * @return airPollutants
  **/
  @ApiModelProperty(value = "")
  public AirPollutants getAirPollutants() {
    return airPollutants;
  }

  public void setAirPollutants(AirPollutants airPollutants) {
    this.airPollutants = airPollutants;
  }

  public Journey lowEmissionZone(LowEmissionZone lowEmissionZone) {
    this.lowEmissionZone = lowEmissionZone;
    return this;
  }

   /**
   * Get lowEmissionZone
   * @return lowEmissionZone
  **/
  @ApiModelProperty(value = "")
  public LowEmissionZone getLowEmissionZone() {
    return lowEmissionZone;
  }

  public void setLowEmissionZone(LowEmissionZone lowEmissionZone) {
    this.lowEmissionZone = lowEmissionZone;
  }

  public Journey durations(Durations durations) {
    this.durations = durations;
    return this;
  }

   /**
   * Get durations
   * @return durations
  **/
  @ApiModelProperty(value = "")
  public Durations getDurations() {
    return durations;
  }

  public void setDurations(Durations durations) {
    this.durations = durations;
  }

  public Journey distances(Distances distances) {
    this.distances = distances;
    return this;
  }

   /**
   * Get distances
   * @return distances
  **/
  @ApiModelProperty(value = "")
  public Distances getDistances() {
    return distances;
  }

  public void setDistances(Distances distances) {
    this.distances = distances;
  }

  public Journey fare(Fare fare) {
    this.fare = fare;
    return this;
  }

   /**
   * Get fare
   * @return fare
  **/
  @ApiModelProperty(required = true, value = "")
  public Fare getFare() {
    return fare;
  }

  public void setFare(Fare fare) {
    this.fare = fare;
  }

  public Journey calendars(List<Calendar> calendars) {
    this.calendars = calendars;
    return this;
  }

  public Journey addCalendarsItem(Calendar calendarsItem) {
    if (this.calendars == null) {
      this.calendars = new ArrayList<Calendar>();
    }
    this.calendars.add(calendarsItem);
    return this;
  }

   /**
   * Get calendars
   * @return calendars
  **/
  @ApiModelProperty(value = "")
  public List<Calendar> getCalendars() {
    return calendars;
  }

  public void setCalendars(List<Calendar> calendars) {
    this.calendars = calendars;
  }

  public Journey sections(List<Section> sections) {
    this.sections = sections;
    return this;
  }

  public Journey addSectionsItem(Section sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<Section>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * Get sections
   * @return sections
  **/
  @ApiModelProperty(value = "")
  public List<Section> getSections() {
    return sections;
  }

  public void setSections(List<Section> sections) {
    this.sections = sections;
  }

  public Journey debug(JourneyDebug debug) {
    this.debug = debug;
    return this;
  }

   /**
   * Get debug
   * @return debug
  **/
  @ApiModelProperty(value = "")
  public JourneyDebug getDebug() {
    return debug;
  }

  public void setDebug(JourneyDebug debug) {
    this.debug = debug;
  }

  public Journey links(List<LinkSchema> links) {
    this.links = links;
    return this;
  }

  public Journey addLinksItem(LinkSchema linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<LinkSchema>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<LinkSchema> getLinks() {
    return links;
  }

  public void setLinks(List<LinkSchema> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Journey journey = (Journey) o;
    return Objects.equals(this.duration, journey.duration) &&
        Objects.equals(this.nbTransfers, journey.nbTransfers) &&
        Objects.equals(this.departureDateTime, journey.departureDateTime) &&
        Objects.equals(this.arrivalDateTime, journey.arrivalDateTime) &&
        Objects.equals(this.requestedDateTime, journey.requestedDateTime) &&
        Objects.equals(this.to, journey.to) &&
        Objects.equals(this.from, journey.from) &&
        Objects.equals(this.type, journey.type) &&
        Objects.equals(this.status, journey.status) &&
        Objects.equals(this.tags, journey.tags) &&
        Objects.equals(this.co2Emission, journey.co2Emission) &&
        Objects.equals(this.airPollutants, journey.airPollutants) &&
        Objects.equals(this.lowEmissionZone, journey.lowEmissionZone) &&
        Objects.equals(this.durations, journey.durations) &&
        Objects.equals(this.distances, journey.distances) &&
        Objects.equals(this.fare, journey.fare) &&
        Objects.equals(this.calendars, journey.calendars) &&
        Objects.equals(this.sections, journey.sections) &&
        Objects.equals(this.debug, journey.debug) &&
        Objects.equals(this.links, journey.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, nbTransfers, departureDateTime, arrivalDateTime, requestedDateTime, to, from, type, status, tags, co2Emission, airPollutants, lowEmissionZone, durations, distances, fare, calendars, sections, debug, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Journey {\n");

    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    nbTransfers: ").append(toIndentedString(nbTransfers)).append("\n");
    sb.append("    departureDateTime: ").append(toIndentedString(departureDateTime)).append("\n");
    sb.append("    arrivalDateTime: ").append(toIndentedString(arrivalDateTime)).append("\n");
    sb.append("    requestedDateTime: ").append(toIndentedString(requestedDateTime)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    co2Emission: ").append(toIndentedString(co2Emission)).append("\n");
    sb.append("    airPollutants: ").append(toIndentedString(airPollutants)).append("\n");
    sb.append("    lowEmissionZone: ").append(toIndentedString(lowEmissionZone)).append("\n");
    sb.append("    durations: ").append(toIndentedString(durations)).append("\n");
    sb.append("    distances: ").append(toIndentedString(distances)).append("\n");
    sb.append("    fare: ").append(toIndentedString(fare)).append("\n");
    sb.append("    calendars: ").append(toIndentedString(calendars)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    debug: ").append(toIndentedString(debug)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

