/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;
import io.swagger.client.model.Admin;
import io.swagger.client.model.CarPark;
import io.swagger.client.model.Coord;
import io.swagger.client.model.LinkSchema;
import io.swagger.client.model.PoiType;
import io.swagger.client.model.Stands;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Poi
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class Poi {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("coord")
  private Coord coord = null;

  @SerializedName("links")
  private List<LinkSchema> links = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("administrative_regions")
  private List<Admin> administrativeRegions = null;

  @SerializedName("poi_type")
  private PoiType poiType = null;

  @SerializedName("properties")
  private Map<String, String> properties = null;

  @SerializedName("address")
  private Address address = null;

  @SerializedName("stands")
  private Stands stands = null;

  @SerializedName("car_park")
  private CarPark carPark = null;

  public Poi id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the object
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Identifier of the object")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Poi name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the object")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Poi coord(Coord coord) {
    this.coord = coord;
    return this;
  }

   /**
   * Get coord
   * @return coord
  **/
  @ApiModelProperty(value = "")
  public Coord getCoord() {
    return coord;
  }

  public void setCoord(Coord coord) {
    this.coord = coord;
  }

  public Poi links(List<LinkSchema> links) {
    this.links = links;
    return this;
  }

  public Poi addLinksItem(LinkSchema linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<LinkSchema>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<LinkSchema> getLinks() {
    return links;
  }

  public void setLinks(List<LinkSchema> links) {
    this.links = links;
  }

  public Poi label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Poi administrativeRegions(List<Admin> administrativeRegions) {
    this.administrativeRegions = administrativeRegions;
    return this;
  }

  public Poi addAdministrativeRegionsItem(Admin administrativeRegionsItem) {
    if (this.administrativeRegions == null) {
      this.administrativeRegions = new ArrayList<Admin>();
    }
    this.administrativeRegions.add(administrativeRegionsItem);
    return this;
  }

   /**
   * Get administrativeRegions
   * @return administrativeRegions
  **/
  @ApiModelProperty(value = "")
  public List<Admin> getAdministrativeRegions() {
    return administrativeRegions;
  }

  public void setAdministrativeRegions(List<Admin> administrativeRegions) {
    this.administrativeRegions = administrativeRegions;
  }

  public Poi poiType(PoiType poiType) {
    this.poiType = poiType;
    return this;
  }

   /**
   * Get poiType
   * @return poiType
  **/
  @ApiModelProperty(value = "")
  public PoiType getPoiType() {
    return poiType;
  }

  public void setPoiType(PoiType poiType) {
    this.poiType = poiType;
  }

  public Poi properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public Poi putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, String>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }

  public Poi address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public Poi stands(Stands stands) {
    this.stands = stands;
    return this;
  }

   /**
   * Get stands
   * @return stands
  **/
  @ApiModelProperty(value = "")
  public Stands getStands() {
    return stands;
  }

  public void setStands(Stands stands) {
    this.stands = stands;
  }

  public Poi carPark(CarPark carPark) {
    this.carPark = carPark;
    return this;
  }

   /**
   * Get carPark
   * @return carPark
  **/
  @ApiModelProperty(value = "")
  public CarPark getCarPark() {
    return carPark;
  }

  public void setCarPark(CarPark carPark) {
    this.carPark = carPark;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Poi poi = (Poi) o;
    return Objects.equals(this.id, poi.id) &&
        Objects.equals(this.name, poi.name) &&
        Objects.equals(this.coord, poi.coord) &&
        Objects.equals(this.links, poi.links) &&
        Objects.equals(this.label, poi.label) &&
        Objects.equals(this.administrativeRegions, poi.administrativeRegions) &&
        Objects.equals(this.poiType, poi.poiType) &&
        Objects.equals(this.properties, poi.properties) &&
        Objects.equals(this.address, poi.address) &&
        Objects.equals(this.stands, poi.stands) &&
        Objects.equals(this.carPark, poi.carPark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, coord, links, label, administrativeRegions, poiType, properties, address, stands, carPark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Poi {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    administrativeRegions: ").append(toIndentedString(administrativeRegions)).append("\n");
    sb.append("    poiType: ").append(toIndentedString(poiType)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    stands: ").append(toIndentedString(stands)).append("\n");
    sb.append("    carPark: ").append(toIndentedString(carPark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

