/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IndividualInformation;
import io.swagger.client.model.SeatsDescription;
import java.io.IOException;

/**
 * RidesharingInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class RidesharingInformation {
  @SerializedName("operator")
  private String operator = null;

  @SerializedName("network")
  private String network = null;

  @SerializedName("driver")
  private IndividualInformation driver = null;

  @SerializedName("seats")
  private SeatsDescription seats = null;

  public RidesharingInformation operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public RidesharingInformation network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }

  public RidesharingInformation driver(IndividualInformation driver) {
    this.driver = driver;
    return this;
  }

   /**
   * Get driver
   * @return driver
  **/
  @ApiModelProperty(value = "")
  public IndividualInformation getDriver() {
    return driver;
  }

  public void setDriver(IndividualInformation driver) {
    this.driver = driver;
  }

  public RidesharingInformation seats(SeatsDescription seats) {
    this.seats = seats;
    return this;
  }

   /**
   * Get seats
   * @return seats
  **/
  @ApiModelProperty(value = "")
  public SeatsDescription getSeats() {
    return seats;
  }

  public void setSeats(SeatsDescription seats) {
    this.seats = seats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RidesharingInformation ridesharingInformation = (RidesharingInformation) o;
    return Objects.equals(this.operator, ridesharingInformation.operator) &&
        Objects.equals(this.network, ridesharingInformation.network) &&
        Objects.equals(this.driver, ridesharingInformation.driver) &&
        Objects.equals(this.seats, ridesharingInformation.seats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operator, network, driver, seats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RidesharingInformation {\n");

    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
    sb.append("    seats: ").append(toIndentedString(seats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

