/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LinkSchema;
import io.swagger.client.model.StopPoint;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * StopDateTime
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class StopDateTime {
  @SerializedName("departure_date_time")
  private String departureDateTime = null;

  @SerializedName("base_departure_date_time")
  private String baseDepartureDateTime = null;

  @SerializedName("arrival_date_time")
  private String arrivalDateTime = null;

  @SerializedName("base_arrival_date_time")
  private String baseArrivalDateTime = null;

  @SerializedName("stop_point")
  private StopPoint stopPoint = null;

  /**
   * Gets or Sets additionalInformations
   */
  @JsonAdapter(AdditionalInformationsEnum.Adapter.class)
  public enum AdditionalInformationsEnum {
    PICK_UP_ONLY("pick_up_only"),

    DROP_OFF_ONLY("drop_off_only"),

    ON_DEMAND_TRANSPORT("on_demand_transport"),

    DATE_TIME_ESTIMATED("date_time_estimated"),

    SKIPPED_STOP("skipped_stop");

    private String value;

    AdditionalInformationsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AdditionalInformationsEnum fromValue(String text) {
      for (AdditionalInformationsEnum b : AdditionalInformationsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AdditionalInformationsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AdditionalInformationsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AdditionalInformationsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AdditionalInformationsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("additional_informations")
  private List<AdditionalInformationsEnum> additionalInformations = new ArrayList<AdditionalInformationsEnum>();

  @SerializedName("links")
  private List<LinkSchema> links = new ArrayList<LinkSchema>();

  /**
   * Gets or Sets dataFreshness
   */
  @JsonAdapter(DataFreshnessEnum.Adapter.class)
  public enum DataFreshnessEnum {
    BASE_SCHEDULE("base_schedule"),

    ADAPTED_SCHEDULE("adapted_schedule"),

    REALTIME("realtime");

    private String value;

    DataFreshnessEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DataFreshnessEnum fromValue(String text) {
      for (DataFreshnessEnum b : DataFreshnessEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DataFreshnessEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DataFreshnessEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DataFreshnessEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DataFreshnessEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("data_freshness")
  private DataFreshnessEnum dataFreshness = null;

  /**
   * Gets or Sets departureOccupancy
   */
  @JsonAdapter(DepartureOccupancyEnum.Adapter.class)
  public enum DepartureOccupancyEnum {
    EMPTY("empty"),

    MANY_SEATS_AVAILABLE("many_seats_available"),

    FEW_SEATS_AVAILABLE("few_seats_available"),

    STANDING_ROOM_ONLY("standing_room_only"),

    CRUSHED_STANDING_ROOM_ONLY("crushed_standing_room_only"),

    FULL("full"),

    NOT_ACCEPTING_PASSENGERS("not_accepting_passengers");

    private String value;

    DepartureOccupancyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DepartureOccupancyEnum fromValue(String text) {
      for (DepartureOccupancyEnum b : DepartureOccupancyEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DepartureOccupancyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DepartureOccupancyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DepartureOccupancyEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DepartureOccupancyEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("departure_occupancy")
  private DepartureOccupancyEnum departureOccupancy = null;

  public StopDateTime departureDateTime(String departureDateTime) {
    this.departureDateTime = departureDateTime;
    return this;
  }

   /**
   * Get departureDateTime
   * @return departureDateTime
  **/
  @ApiModelProperty(value = "")
  public String getDepartureDateTime() {
    return departureDateTime;
  }

  public void setDepartureDateTime(String departureDateTime) {
    this.departureDateTime = departureDateTime;
  }

  public StopDateTime baseDepartureDateTime(String baseDepartureDateTime) {
    this.baseDepartureDateTime = baseDepartureDateTime;
    return this;
  }

   /**
   * Get baseDepartureDateTime
   * @return baseDepartureDateTime
  **/
  @ApiModelProperty(value = "")
  public String getBaseDepartureDateTime() {
    return baseDepartureDateTime;
  }

  public void setBaseDepartureDateTime(String baseDepartureDateTime) {
    this.baseDepartureDateTime = baseDepartureDateTime;
  }

  public StopDateTime arrivalDateTime(String arrivalDateTime) {
    this.arrivalDateTime = arrivalDateTime;
    return this;
  }

   /**
   * Get arrivalDateTime
   * @return arrivalDateTime
  **/
  @ApiModelProperty(value = "")
  public String getArrivalDateTime() {
    return arrivalDateTime;
  }

  public void setArrivalDateTime(String arrivalDateTime) {
    this.arrivalDateTime = arrivalDateTime;
  }

  public StopDateTime baseArrivalDateTime(String baseArrivalDateTime) {
    this.baseArrivalDateTime = baseArrivalDateTime;
    return this;
  }

   /**
   * Get baseArrivalDateTime
   * @return baseArrivalDateTime
  **/
  @ApiModelProperty(value = "")
  public String getBaseArrivalDateTime() {
    return baseArrivalDateTime;
  }

  public void setBaseArrivalDateTime(String baseArrivalDateTime) {
    this.baseArrivalDateTime = baseArrivalDateTime;
  }

  public StopDateTime stopPoint(StopPoint stopPoint) {
    this.stopPoint = stopPoint;
    return this;
  }

   /**
   * Get stopPoint
   * @return stopPoint
  **/
  @ApiModelProperty(value = "")
  public StopPoint getStopPoint() {
    return stopPoint;
  }

  public void setStopPoint(StopPoint stopPoint) {
    this.stopPoint = stopPoint;
  }

  public StopDateTime additionalInformations(List<AdditionalInformationsEnum> additionalInformations) {
    this.additionalInformations = additionalInformations;
    return this;
  }

  public StopDateTime addAdditionalInformationsItem(AdditionalInformationsEnum additionalInformationsItem) {
    this.additionalInformations.add(additionalInformationsItem);
    return this;
  }

   /**
   * Get additionalInformations
   * @return additionalInformations
  **/
  @ApiModelProperty(required = true, value = "")
  public List<AdditionalInformationsEnum> getAdditionalInformations() {
    return additionalInformations;
  }

  public void setAdditionalInformations(List<AdditionalInformationsEnum> additionalInformations) {
    this.additionalInformations = additionalInformations;
  }

  public StopDateTime links(List<LinkSchema> links) {
    this.links = links;
    return this;
  }

  public StopDateTime addLinksItem(LinkSchema linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "")
  public List<LinkSchema> getLinks() {
    return links;
  }

  public void setLinks(List<LinkSchema> links) {
    this.links = links;
  }

  public StopDateTime dataFreshness(DataFreshnessEnum dataFreshness) {
    this.dataFreshness = dataFreshness;
    return this;
  }

   /**
   * Get dataFreshness
   * @return dataFreshness
  **/
  @ApiModelProperty(value = "")
  public DataFreshnessEnum getDataFreshness() {
    return dataFreshness;
  }

  public void setDataFreshness(DataFreshnessEnum dataFreshness) {
    this.dataFreshness = dataFreshness;
  }

  public StopDateTime departureOccupancy(DepartureOccupancyEnum departureOccupancy) {
    this.departureOccupancy = departureOccupancy;
    return this;
  }

   /**
   * Get departureOccupancy
   * @return departureOccupancy
  **/
  @ApiModelProperty(value = "")
  public DepartureOccupancyEnum getDepartureOccupancy() {
    return departureOccupancy;
  }

  public void setDepartureOccupancy(DepartureOccupancyEnum departureOccupancy) {
    this.departureOccupancy = departureOccupancy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopDateTime stopDateTime = (StopDateTime) o;
    return Objects.equals(this.departureDateTime, stopDateTime.departureDateTime) &&
        Objects.equals(this.baseDepartureDateTime, stopDateTime.baseDepartureDateTime) &&
        Objects.equals(this.arrivalDateTime, stopDateTime.arrivalDateTime) &&
        Objects.equals(this.baseArrivalDateTime, stopDateTime.baseArrivalDateTime) &&
        Objects.equals(this.stopPoint, stopDateTime.stopPoint) &&
        Objects.equals(this.additionalInformations, stopDateTime.additionalInformations) &&
        Objects.equals(this.links, stopDateTime.links) &&
        Objects.equals(this.dataFreshness, stopDateTime.dataFreshness) &&
        Objects.equals(this.departureOccupancy, stopDateTime.departureOccupancy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departureDateTime, baseDepartureDateTime, arrivalDateTime, baseArrivalDateTime, stopPoint, additionalInformations, links, dataFreshness, departureOccupancy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopDateTime {\n");

    sb.append("    departureDateTime: ").append(toIndentedString(departureDateTime)).append("\n");
    sb.append("    baseDepartureDateTime: ").append(toIndentedString(baseDepartureDateTime)).append("\n");
    sb.append("    arrivalDateTime: ").append(toIndentedString(arrivalDateTime)).append("\n");
    sb.append("    baseArrivalDateTime: ").append(toIndentedString(baseArrivalDateTime)).append("\n");
    sb.append("    stopPoint: ").append(toIndentedString(stopPoint)).append("\n");
    sb.append("    additionalInformations: ").append(toIndentedString(additionalInformations)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    dataFreshness: ").append(toIndentedString(dataFreshness)).append("\n");
    sb.append("    departureOccupancy: ").append(toIndentedString(departureOccupancy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

