/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Coord;
import io.swagger.client.model.VehicleJourney;
import java.io.IOException;

/**
 * VehicleJourneyPositions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class VehicleJourneyPositions {
  @SerializedName("vehicle_journey")
  private VehicleJourney vehicleJourney = null;

  @SerializedName("coord")
  private Coord coord = null;

  @SerializedName("bearing")
  private Integer bearing = null;

  @SerializedName("speed")
  private Integer speed = null;

  @SerializedName("data_freshness")
  private String dataFreshness = null;

  @SerializedName("occupancy")
  private String occupancy = null;

  @SerializedName("feed_created_at")
  private String feedCreatedAt = null;

  public VehicleJourneyPositions vehicleJourney(VehicleJourney vehicleJourney) {
    this.vehicleJourney = vehicleJourney;
    return this;
  }

   /**
   * Get vehicleJourney
   * @return vehicleJourney
  **/
  @ApiModelProperty(value = "")
  public VehicleJourney getVehicleJourney() {
    return vehicleJourney;
  }

  public void setVehicleJourney(VehicleJourney vehicleJourney) {
    this.vehicleJourney = vehicleJourney;
  }

  public VehicleJourneyPositions coord(Coord coord) {
    this.coord = coord;
    return this;
  }

   /**
   * Get coord
   * @return coord
  **/
  @ApiModelProperty(value = "")
  public Coord getCoord() {
    return coord;
  }

  public void setCoord(Coord coord) {
    this.coord = coord;
  }

  public VehicleJourneyPositions bearing(Integer bearing) {
    this.bearing = bearing;
    return this;
  }

   /**
   * Get bearing
   * @return bearing
  **/
  @ApiModelProperty(value = "")
  public Integer getBearing() {
    return bearing;
  }

  public void setBearing(Integer bearing) {
    this.bearing = bearing;
  }

  public VehicleJourneyPositions speed(Integer speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @ApiModelProperty(value = "")
  public Integer getSpeed() {
    return speed;
  }

  public void setSpeed(Integer speed) {
    this.speed = speed;
  }

  public VehicleJourneyPositions dataFreshness(String dataFreshness) {
    this.dataFreshness = dataFreshness;
    return this;
  }

   /**
   * Get dataFreshness
   * @return dataFreshness
  **/
  @ApiModelProperty(value = "")
  public String getDataFreshness() {
    return dataFreshness;
  }

  public void setDataFreshness(String dataFreshness) {
    this.dataFreshness = dataFreshness;
  }

  public VehicleJourneyPositions occupancy(String occupancy) {
    this.occupancy = occupancy;
    return this;
  }

   /**
   * Get occupancy
   * @return occupancy
  **/
  @ApiModelProperty(value = "")
  public String getOccupancy() {
    return occupancy;
  }

  public void setOccupancy(String occupancy) {
    this.occupancy = occupancy;
  }

  public VehicleJourneyPositions feedCreatedAt(String feedCreatedAt) {
    this.feedCreatedAt = feedCreatedAt;
    return this;
  }

   /**
   * Get feedCreatedAt
   * @return feedCreatedAt
  **/
  @ApiModelProperty(value = "")
  public String getFeedCreatedAt() {
    return feedCreatedAt;
  }

  public void setFeedCreatedAt(String feedCreatedAt) {
    this.feedCreatedAt = feedCreatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleJourneyPositions vehicleJourneyPositions = (VehicleJourneyPositions) o;
    return Objects.equals(this.vehicleJourney, vehicleJourneyPositions.vehicleJourney) &&
        Objects.equals(this.coord, vehicleJourneyPositions.coord) &&
        Objects.equals(this.bearing, vehicleJourneyPositions.bearing) &&
        Objects.equals(this.speed, vehicleJourneyPositions.speed) &&
        Objects.equals(this.dataFreshness, vehicleJourneyPositions.dataFreshness) &&
        Objects.equals(this.occupancy, vehicleJourneyPositions.occupancy) &&
        Objects.equals(this.feedCreatedAt, vehicleJourneyPositions.feedCreatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vehicleJourney, coord, bearing, speed, dataFreshness, occupancy, feedCreatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleJourneyPositions {\n");

    sb.append("    vehicleJourney: ").append(toIndentedString(vehicleJourney)).append("\n");
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("    bearing: ").append(toIndentedString(bearing)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    dataFreshness: ").append(toIndentedString(dataFreshness)).append("\n");
    sb.append("    occupancy: ").append(toIndentedString(occupancy)).append("\n");
    sb.append("    feedCreatedAt: ").append(toIndentedString(feedCreatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

