/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results
 *
 * OpenAPI spec version: v15.75.4
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gdamiens.website.idfm.navitia.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Line;
import io.swagger.client.model.VehicleJourneyPositions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VehiclePositions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-01-15T18:02:06.472Z")
public class VehiclePositions {
  @SerializedName("line")
  private Line line = null;

  @SerializedName("vehicle_journey_positions")
  private List<VehicleJourneyPositions> vehicleJourneyPositions = null;

  public VehiclePositions line(Line line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @ApiModelProperty(value = "")
  public Line getLine() {
    return line;
  }

  public void setLine(Line line) {
    this.line = line;
  }

  public VehiclePositions vehicleJourneyPositions(List<VehicleJourneyPositions> vehicleJourneyPositions) {
    this.vehicleJourneyPositions = vehicleJourneyPositions;
    return this;
  }

  public VehiclePositions addVehicleJourneyPositionsItem(VehicleJourneyPositions vehicleJourneyPositionsItem) {
    if (this.vehicleJourneyPositions == null) {
      this.vehicleJourneyPositions = new ArrayList<VehicleJourneyPositions>();
    }
    this.vehicleJourneyPositions.add(vehicleJourneyPositionsItem);
    return this;
  }

   /**
   * Get vehicleJourneyPositions
   * @return vehicleJourneyPositions
  **/
  @ApiModelProperty(value = "")
  public List<VehicleJourneyPositions> getVehicleJourneyPositions() {
    return vehicleJourneyPositions;
  }

  public void setVehicleJourneyPositions(List<VehicleJourneyPositions> vehicleJourneyPositions) {
    this.vehicleJourneyPositions = vehicleJourneyPositions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehiclePositions vehiclePositions = (VehiclePositions) o;
    return Objects.equals(this.line, vehiclePositions.line) &&
        Objects.equals(this.vehicleJourneyPositions, vehiclePositions.vehicleJourneyPositions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line, vehicleJourneyPositions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehiclePositions {\n");

    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    vehicleJourneyPositions: ").append(toIndentedString(vehicleJourneyPositions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

