name: Test Coveralls
on: ["push"]
jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: 🛠 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Install dependencies
        run: mvn install
      - name: Maven Test
        run: mvn test
      - name: Run test-coverage
        with:
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn clean test jacoco:report coveralls:report -DrepoToken=yourcoverallsprojectrepositorytoken
